### ISSUE TITLE
Recreate website from GitHub

### ISSUE THREAD

**Issue by gleporeNARA** [HistoryAtState/travels#15]
This may be a dumb question, but how does one go from the GitHub to the website? Somehow the files here are combined with other files to create https://history.state.gov/departmenthistory/travels. What is the process for this to happen? Are all of the files (logos, etc.) on the GitHub?

Thanks.

**Comment by joewiz** [comment]
@gleporeNARA The application that exposes this data to history.state.gov is https://github.com/HistoryAtState/hsg-shell. The relevant application logic can be found in https://github.com/HistoryAtState/hsg-shell/blob/master/modules/pocom-html.xqm. To build and deploy a full clone of the website on one's own computer, see https://github.com/HistoryAtState/hsg-project.

**Comment by gleporeNARA** [comment]
Got it. Thanks.

**Comment by gleporeNARA** [comment]
Wait, not sure if I've got. Would that result in a usable website (similar to harvesting the website from the server with a webcrawler) or would it result in creating the source files, which would obviously still contain external links, etc.

We're looking to obtain a copy of the website that would be usable to third party researchers way down the line.

**Comment by joewiz** [comment]
@gleporeNARA The former. Using hsg-project, you will have a completely functional and interactive instance of history.state.gov running on your local machine. Without a proxy server, the URLs for history.state.gov pages will begin with http://localhost:8080/exist/apps/hsg-shell. On our production servers, we use nginx to forward requests for `/` to `/exist/apps/hsg-shell/`.
